# Generated by Django 2.2.4 on 2019-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='firstname')),
                ('occupation', models.CharField(blank=True, max_length=128, verbose_name='Occupation')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('mail_address', models.CharField(max_length=150, verbose_name='Mail Address')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
            ],
        ),
    ]
